name: urban_center

dependencies:
  - plotly
  - numpy
  - protobuf>=3.6.0
  - libpysal
  - pysal
  - pip
  - pip:
      - pygeos
      - geopandas==0.10.2
      - click==8
      - streamlit_authenticator
