name: urban_center

dependencies:
  - plotly
  - numpy
  - protobuf>=3.6.0
  - libpysal
  - pysal
  - pip
  - pip:
      - gdal==3.2.2
      - pyproj==3.0.1
      - fiona==1.8.18
      - shapely==1.7.1
      - geopandas
      - click==8
      - streamlit_authenticator
