name: urban_center

dependencies:
  - plotly
  - numpy
  - protobuf>=3.6.0
  - libpysal
  - pysal
  - pip
  - sqlalchemy
  - psycopg2
  - pip:
      - geopandas
      - click==8
      - streamlit_authenticator
