name: urban_center

dependencies:
  - plotly
  - numpy
  - protobuf>=3.6.0
  - pysal
  - libpysal
  - pip
  - pip:
      - geopandas
      - streamlit_authenticator
      - kaleido
      - scipy==1.8.0
