name: urban_center
channels:
  - conda-forge
dependencies:
  - plotly
  - numpy
  - protobuf>=3.6.0
  - pip
  - pip:
      - geopandas
      - click==8
      - streamlit_authenticator
# - pysal
# - libpysal
