name: urban_center

dependencies:
  - plotly
  - numpy
  - pygeos
  - pysal
  - libpysal
  - protobuf>=3.6.0
  - pip
  - pip:
      - geopandas
      - click==8
      - streamlit_authenticator
      - pandana
