name: urban_center

dependencies:
  - plotly
  - protobuf>=3.6.0
  - pysal
  - libpysal
  - pip
  - pip:
      - python==3.8
      - numpy==1.22.4
      - geopandas
      - click==8
      - streamlit_authenticator
