name: urban_center

dependencies:
  - plotly
  - numpy
  - protobuf>=3.6.0
  - libpysal
  - pysal
  - pip
  - pip:
      - geopandas==0.9.0
      - click==8
      - streamlit_authenticator
      - fiona==1.8.20
