credentials:
  usernames:
    zhanl022:
      email: 
      name: Zhang Liyao
      password: $2b$12$DKeytYjADsuShp0jGxbhLOCB3iiMXYecZhu4ILh20mGIKHptC8mP6
    xiaoj022:
      email:
      name: Xiao Junyao
      password: $2b$12$lEcnTReB9AoIgXVPbXkx5.g1H64RHFnQmbhdqzKHOmts2xVrPvqiq
    huanz022:
      email:
      name: Huang Zhihui
      password: $2b$12$rvVCQne2Ck18XK5xFqm8PeRVd78RqP0mqQZ9RMpAW1GnhfUWkcWAe
    zhent022:
      email:
      name: Zheng Ting
      password: $2b$12$GzcDLTa1wLXA2ShHSl8V4.dAgF2XtHOnkWwFwvoHF.6KWHoMx/8Dq
    lij022:
      email:
      name: Li Jiayun
      password: $2b$12$0R0XL/Btn5B4upY24Mt3f.2Q77l4f8J6vfx0ZBFtDsSu6SAoy8J3a
cookie:
  expiry_days: 30
  key: 'sfh3ef&f70qa#kwdJ'
  name: cookie02
preauthorized:
  emails:
  - 
